# Generated by Django 2.0 on 2018-12-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.User')),
                ('following_count', models.IntegerField()),
                ('following_users', models.ManyToManyField(related_name='following_users', to='main.User')),
                ('recommendations', models.ManyToManyField(related_name='recommendations', to='main.User')),
            ],
            bases=('main.user',),
        ),
    ]
