# Generated by Django 2.0 on 2018-12-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField()),
                ('system_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_system_user', to='main.SystemUser')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='main.User'),
        ),
    ]
