# Generated by Django 2.0 on 2018-12-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='following_users',
            field=models.ManyToManyField(related_name='following_users', to='main.User'),
        ),
    ]
