# Generated by Django 2.0 on 2018-12-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181229_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='favorites_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
