# Generated by Django 2.0 on 2018-12-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_systemuser_favorites_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='favorites_count',
            new_name='favourites_count',
        ),
    ]
