# Generated by Django 2.0 on 2018-12-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181229_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='system_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_system_user', to='main.SystemUser'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='main.User'),
        ),
    ]
