# Generated by Django 2.0 on 2019-01-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190102_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='following_users',
        ),
        migrations.AddField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='following', to='main.User'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='system_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_system_user', to='main.User'),
        ),
    ]
