# Generated by Django 2.0 on 2019-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190121_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='favourites_count',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='following_count',
        ),
        migrations.AddField(
            model_name='user',
            name='favourites_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
